/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 * Copyright(C) 2026, Mickael Palma / MP Consulting. All rights reserved.
 *
 * server.js: @mp-consulting/homebridge-unifi-protect webUI server API.
 */
'use strict';

import { featureOptionCategories, featureOptions } from '../dist/protect-options.js';
import { HomebridgePluginUiServer } from '@homebridge/plugin-ui-utils';
import { ProtectApi } from 'unifi-protect';
import { discoverOnvifEndpoints } from './onvif.js';
import dgram from 'node:dgram';
import https from 'node:https';
import os from 'node:os';
import util from 'node:util';

// Validate a controller address, rejecting loopback, link-local, and unspecified addresses.
function isValidAddress(address) {

  if(!address || (typeof address !== 'string')) {

    return false;
  }

  const trimmed = address.trim().toLowerCase();

  if(!trimmed || (trimmed === 'localhost') || trimmed.startsWith('127.') || trimmed.startsWith('169.254.') || (trimmed === '0.0.0.0') ||
    trimmed.startsWith('[') || trimmed.includes('::')) {

    return false;
  }

  return true;
}

// Number of adjacent /24 subnets to scan in each direction from each local interface.
// A value of 5 means scanning ±5 subnets (up to 2,540 unicast probes per local subnet).
// Only used for discovering UniFi devices on routed subnets where broadcasts don't reach.
const ADJACENT_SUBNET_RANGE = 5;
const DISCOVERY_TIMEOUT = 5000;
const UBNT_DISCOVERY_PORT = 10001;

// Ubiquiti L2 Discovery Protocol: send a 4-byte packet, devices respond with TLV data.
const UBNT_DISCOVERY_PACKET = globalThis.Buffer.from([ 0x01, 0x00, 0x00, 0x00 ]);

// TLV field types in the Ubiquiti discovery response.
const UBNT_TLV = {

  FIRMWARE: 0x03,     // Firmware version string
  HOSTNAME: 0x0B,     // Device hostname
  MAC_IP: 0x02,       // 6-byte MAC + 4-byte IP
  MODEL_LONG: 0x14,   // Full model name
  MODEL_SHORT: 0x0C,   // Short model name (e.g. "UNVR")
};

class PluginUiServer extends HomebridgePluginUiServer {

  errorInfo;

  constructor() {

    super();

    this.errorInfo = '';

    // Register getErrorMessage() with the Homebridge server API.
    this.#registerGetErrorMessage();

    // Register getDevices() with the Homebridge server API.
    this.#registerGetDevices();

    // Register getOptions() with the Homebridge server API.
    this.#registerGetOptions();

    // Register discover() with the Homebridge server API.
    this.#registerDiscover();

    // Register checkStatus() with the Homebridge server API.
    this.#registerCheckStatus();

    // Register discoverOnvif() with the Homebridge server API.
    this.#registerDiscoverOnvif();

    this.ready();
  }

  // Register the discoverOnvif() webUI server API endpoint. Used by the third-party camera URL override panel to auto-populate the RTSP and snapshot
  // URLs from a camera's IP and credentials, mirroring UniFi Protect's own Advanced Adoption flow.
  #registerDiscoverOnvif() {

    this.onRequest('/discoverOnvif', async (payload) => {

      try {

        const result = await discoverOnvifEndpoints({

          host: payload?.host?.trim(),
          password: payload?.password ?? '',
          port: payload?.port ? Number(payload.port) : undefined,
          servicePath: payload?.servicePath?.trim(),
          username: payload?.username?.trim(),
        });

        return { ok: true, ...result };
      } catch(err) {

        return { error: err instanceof Error ? err.message : String(err), ok: false };
      }
    });
  }

  // Register the getErrorMessage() webUI server API endpoint.
  #registerGetErrorMessage() {

    // Return the most recent error message generated by the Protect API.
    this.onRequest('/getErrorMessage', () => this.errorInfo);
  }

  // Register the getDevices() webUI server API endpoint.
  #registerGetDevices() {

    let ufpApi;

    // Return the list of Protect devices.
    this.onRequest('/getDevices', async (controller) => {

      // Validate the controller address before attempting a connection.
      if(!isValidAddress(controller.address)) {

        return [];
      }

      try {

        const log = {

          debug: () => {},
          error: (message, parameters = []) => {

            // Save the error to inform the user in the webUI.
            this.errorInfo = util.format(message, ...(Array.isArray(parameters) ? parameters : [parameters]));


            console.error(this.errorInfo);
          },
          info: () => {},
          warn: () => {},
        };

        // Connect to the Protect controller.
        ufpApi = new ProtectApi(log);

        if(!(await ufpApi.login(controller.address, controller.username, controller.password))) {

          return [];
        }

        // Bootstrap the controller. It will emit a message once it's received the bootstrap JSON, or you can alternatively wait for the Promise to resolve.
        if(!(await ufpApi.getBootstrap())) {

          return [];
        }

        const bootstrap = ufpApi.bootstrap;

        bootstrap.cameras = bootstrap.cameras.filter(x => !x.isAdoptedByOther && x.isAdopted);
        bootstrap.chimes = bootstrap.chimes.filter(x => !x.isAdoptedByOther && x.isAdopted);
        bootstrap.lights = bootstrap.lights.filter(x => !x.isAdoptedByOther && x.isAdopted);
        bootstrap.sensors = bootstrap.sensors.filter(x => !x.isAdoptedByOther && x.isAdopted);
        bootstrap.viewers = bootstrap.viewers.filter(x => !x.isAdoptedByOther && x.isAdopted);

        bootstrap.cameras.sort((a, b) => {

          const aCase = (a.name ?? a.marketName).toLowerCase();
          const bCase = (b.name ?? b.marketName).toLowerCase();

          return aCase > bCase ? 1 : (bCase > aCase ? -1 : 0);
        });

        bootstrap.chimes.sort((a, b) => {

          const aCase = (a.name ?? a.marketName).toLowerCase();
          const bCase = (b.name ?? b.marketName).toLowerCase();

          return aCase > bCase ? 1 : (bCase > aCase ? -1 : 0);
        });

        bootstrap.lights.sort((a, b) => {

          const aCase = (a.name ?? a.marketName).toLowerCase();
          const bCase = (b.name ?? b.marketName).toLowerCase();

          return aCase > bCase ? 1 : (bCase > aCase ? -1 : 0);
        });

        bootstrap.sensors.sort((a, b) => {

          const aCase = (a.name ?? a.marketName).toLowerCase();
          const bCase = (b.name ?? b.marketName).toLowerCase();

          return aCase > bCase ? 1 : (bCase > aCase ? -1 : 0);
        });

        bootstrap.viewers.sort((a, b) => {

          const aCase = (a.name ?? a.marketName).toLowerCase();
          const bCase = (b.name ?? b.marketName).toLowerCase();

          return aCase > bCase ? 1 : (bCase > aCase ? -1 : 0);
        });

        return [ ufpApi.bootstrap.nvr, ...ufpApi.bootstrap.cameras, ...ufpApi.bootstrap.chimes, ...ufpApi.bootstrap.lights, ...ufpApi.bootstrap.sensors,
          ...ufpApi.bootstrap.viewers ];
      } catch(err) {


        console.log(err);

        // Return nothing if we error out for some reason.
        return [];
      } finally {

        ufpApi?.logout();
      }
    });
  }

  // Register the getOptions() webUI server API endpoint.
  #registerGetOptions() {

    // Return the list of options configured for a given Protect device.
    this.onRequest('/getOptions', () => ({ categories: featureOptionCategories, options: featureOptions }));
  }

  // Register the discover() webUI server API endpoint using the Ubiquiti L2 Discovery Protocol.
  #registerDiscover() {

    this.onRequest('/discover', () => {

      return new Promise((resolve) => {

        const devices = [];
        const seen = new Set();

        const socket = dgram.createSocket({ reuseAddr: true, type: 'udp4' });

        socket.on('message', (msg) => {

          // Parse the Ubiquiti discovery response (TLV format after 4-byte header).
          if(msg.length < 4) {
            return;
          }

          const device = {};
          let offset = 4;

          while(offset + 3 <= msg.length) {

            const type = msg[offset];
            const length = msg.readUInt16BE(offset + 1);

            offset += 3;

            if(offset + length > msg.length) {
              break;
            }

            const value = msg.subarray(offset, offset + length);

            switch(type) {

              case UBNT_TLV.MAC_IP:

                if(length >= 10) {

                  device.mac = [...value.subarray(0, 6)].map(b => b.toString(16).padStart(2, '0')).join(':');
                  device.ip = value[6] + '.' + value[7] + '.' + value[8] + '.' + value[9];
                }

                break;

              case UBNT_TLV.HOSTNAME:

                device.hostname = value.toString('utf8');

                break;

              case UBNT_TLV.MODEL_SHORT:

                device.model = value.toString('utf8');

                break;

              case UBNT_TLV.MODEL_LONG:

                device.modelLong = value.toString('utf8');

                break;

              case UBNT_TLV.FIRMWARE:

                device.firmware = value.toString('utf8');

                break;

              default:

                break;
            }

            offset += length;
          }

          if(device.ip && !seen.has(device.ip)) {

            seen.add(device.ip);

            devices.push({

              firmware: device.firmware || '',
              ip: device.ip,
              mac: device.mac || '',
              model: device.model || '',
              modelLong: device.modelLong || '',
              name: device.hostname || device.model || device.ip,
            });
          }
        });

        socket.on('error', () => {

          try {
            socket.close();
          } catch{ /* ignore */ }
          resolve([]);
        });

        socket.bind(() => {

          socket.setBroadcast(true);

          // Broadcast to all local subnet broadcast addresses to reach devices on directly-connected subnets.
          const broadcastAddresses = new Set(['255.255.255.255']);
          const localSubnets = [];

          for(const iface of Object.values(os.networkInterfaces())) {

            for(const info of (iface || [])) {

              if((info.family === 'IPv4') && !info.internal) {

                const ipParts = info.address.split('.').map(Number);
                const maskParts = info.netmask.split('.').map(Number);
                const broadcast = ipParts.map((ip, i) => (ip | (~maskParts[i] & 0xFF))).join('.');

                broadcastAddresses.add(broadcast);

                // Track /24+ subnets for adjacent unicast scanning.
                if(maskParts[2] === 255) {

                  localSubnets.push([ ipParts[0], ipParts[1], ipParts[2] ]);
                }
              }
            }
          }

          for(const addr of broadcastAddresses) {

            socket.send(UBNT_DISCOVERY_PACKET, 0, UBNT_DISCOVERY_PACKET.length, UBNT_DISCOVERY_PORT, addr);
          }

          // Unicast scan adjacent /24 subnets to find devices across routed subnets (broadcasts don't cross routers).
          const scannedSubnets = new Set(localSubnets.map(s => s.join('.')));

          for(const [ a, b, c ] of localSubnets) {

            for(let offset = -ADJACENT_SUBNET_RANGE; offset <= ADJACENT_SUBNET_RANGE; offset++) {

              const adjacentC = c + offset;

              if((adjacentC < 0) || (adjacentC > 255)) {

                continue;
              }

              const subnetKey = a + '.' + b + '.' + adjacentC;

              if(scannedSubnets.has(subnetKey)) {

                continue;
              }

              scannedSubnets.add(subnetKey);

              for(let host = 1; host <= 254; host++) {

                socket.send(UBNT_DISCOVERY_PACKET, 0, UBNT_DISCOVERY_PACKET.length, UBNT_DISCOVERY_PORT, a + '.' + b + '.' + adjacentC + '.' + host);
              }
            }
          }
        });

        // Stop after timeout and return results.
        globalThis.setTimeout(() => {

          try {
            socket.close();
          } catch{ /* ignore */ }
          resolve(devices);
        }, DISCOVERY_TIMEOUT);
      });
    });
  }

  // Register the checkStatus() webUI server API endpoint.
  #registerCheckStatus() {

    this.onRequest('/checkStatus', (payload) => {

      return new Promise((resolve) => {

        if(!isValidAddress(payload?.address)) {

          resolve({ online: false });

          return;
        }

        const req = https.request({

          hostname: payload.address,
          method: 'HEAD',
          path: '/',
          port: 443,
          rejectUnauthorized: false,
          timeout: 5000,
        }, () => resolve({ online: true }));

        req.on('error', () => resolve({ online: false }));
        req.on('timeout', () => {

          req.destroy();
          resolve({ online: false });
        });

        req.end();
      });
    });
  }
}

(() => new PluginUiServer())();
